name: Release
on:
  workflow_dispatch:
  release:
    types:
      - published
permissions:
  contents: write

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare dependencies
        run: |
          echo "Get Node version"
          node --version
          echo "Install Yarn"
          npm install -g corepack@0.34.0
          echo "Check that we're running latest yarn..."
          which yarn
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node-version }}
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the project
        run: yarn rollup
      - name: Upload built source
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mass-card.js